# Generated by Django 5.0.7 on 2024-07-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applicant_name',
            field=models.CharField(default='Unknown Applicant', max_length=200),
        ),
    ]
