# Generated by Django 5.0.7 on 2024-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_applicant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='applicant_name',
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff',
            field=models.CharField(default='Unknown Plaintiff', max_length=200),
        ),
    ]
