# Generated by Django 5.0.7 on 2024-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_case_applicant_name_case_plaintiff'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.CharField(default='Unknown Defendant', max_length=200),
        ),
    ]
